[package]
name = "engine"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
blake3.workspace = true
chain-io.workspace = true
clap.workspace = true
det.workspace = true
telemetry.workspace = true
tokio = { workspace = true, features = ["rt", "sync"] }
tracing.workspace = true
types.workspace = true

[dev-dependencies]
alloy-primitives.workspace = true

[lints]
workspace = true
