[package]
name = "proto"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
pbjson.workspace = true
prost.workspace = true
serde.workspace = true

[build-dependencies]
pbjson-build.workspace = true
prost.workspace = true
prost-build.workspace = true
protox.workspace = true

[lints]
workspace = true
